exp_name: 'vq2d_baseline_transformer_3_torch_spatial_8_time_5_lr_0.0001_wgiou_0.3_pe3d_sin_aug_both_stronger'
exp_group: 'vq2d_transformer'
output_dir: './output/'
log_dir: './log'
workers: 8
print_freq: 100
vis_freq: 1000
eval_vis_freq: 100
seed: 42

# dataset config
dataset:
  name: 'ego4d_vq2d'
  query_size: 256
  clip_size_fine: 256
  clip_size_coarse: 256
  clip_num_frames: 30
  clip_sampling: 'rand'
  clip_reader: 'decord_balance'   # balance positive and negative samples
  frame_interval: 1

# model config
model:
  backbone_name: 'dino'
  backbone_type: 'vitb8'
  bakcbone_use_mae_weight: False
  fix_backbone: True
  num_transformer: 3
  type_transformer: 'global'
  resolution_transformer: 8
  pe_transformer: 'zero'
  window_transformer: 5

# loss config
loss:
  weight_bbox_center: 1.0
  weight_bbox_hw: 1.0
  weight_bbox_giou: 0.3
  weight_bbox_ratio: 1.0
  weight_prob: 1.0
  prob_bce_weight: [0.3, 0.7]

# training config
train:
  resume: True
  batch_size: 4
  total_iteration: 30000
  lr: 0.0001
  weight_decay: 0.005
  schedualr_milestones: [7000, 14000, 20000, 25000]
  schedular_gamma: 0.3
  grad_max: 20.0
  accumulation_step: 1
  aug_clip: True
  aug_query: True
  aug_brightness: 0.3
  aug_contrast: 0.3
  aug_saturation: 0.2
  aug_crop_scale: 0.8
  aug_crop_ratio_min: 0.8
  aug_crop_ratio_max: 1.2
  aug_affine_degree: 90
  aug_affine_translate: 0.2
  aug_affine_scale_min: 0.8
  aug_affine_scale_max: 1.2
  aug_affine_shear_min: -15.0
  aug_affine_shear_max: 15.0
  aug_prob_color: 1.0
  aug_prob_flip: 0.5
  aug_prob_crop: 1.0
  aug_prob_affine: 1.0

# test config
test:
  batch_size: 4
  compute_metric: True